# makefile for all Media Kit sample code

SUBMAKES = \
	MediaFile

LEAFDIRS = \
	BitmapWriter \
	CodyCam \
	FilmStrip \
	LoggingConsumerApp \
	MediaConverter \
	Mix-A-Lot/Mix-A-Lot \
	ParameterSample \
	ToneProducer

default .DEFAULT:
	-@for f in $(SUBMAKES); do \
		$(MAKE) -C $$f -f makefile.all $@; \
	done
	-@for f in $(LEAFDIRS); do \
		$(MAKE) -C $$f $@; \
	done
